#import <Foundation/Foundation.h>
#import "UADSHeaderBiddingTokenReaderWithSCARSignalsBaseStrategy.h"

NS_ASSUME_NONNULL_BEGIN

@interface UADSHeaderBiddingTokenReaderWithSCARSignalsLazyStrategy : UADSHeaderBiddingTokenReaderWithSCARSignalsBaseStrategy

@end

NS_ASSUME_NONNULL_END
