#import "UADSConfigurationLoaderIntegrationTestsBase.h"

NS_ASSUME_NONNULL_BEGIN

@interface UADSConfigurationLoaderIntegrationMetricsBatchTests : UADSConfigurationLoaderIntegrationTestsBase

@end

NS_ASSUME_NONNULL_END
