# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_test do
    clear_derived_data
    scan(
      scheme: "UnityAds",
      code_coverage: true,
      project: "UnityAds.xcodeproj",
      reset_simulator: true
    )
  end
  
  desc "Run unit tests on device specified by IPHONE_DEVICE_ID environment variable"
  lane :unit_test_on_device do
    clear_derived_data
    scan(
      scheme: "UnityAds",
      code_coverage: true,
      project: "UnityAds.xcodeproj",
      destination: "platform=iOS,id=" + ENV["IPHONE_DEVICE_ID"]
    )
  end

  desc "Run integration tests"
  lane :integration_test do
    clear_derived_data
    scan(
      scheme: "UnityAdsIntegrationTests",
      code_coverage: true,
      project: "UnityAds.xcodeproj",
      reset_simulator: true
    )
  end

  desc "Run integration tests on device specified by IPHONE_DEVICE_ID environment variable"
  lane :integration_test_on_device do
    clear_derived_data
    scan(
      scheme: "UnityAdsIntegrationTests",
      code_coverage: true,
      project: "UnityAds.xcodeproj",
      destination: "platform=iOS,id=" + ENV["IPHONE_DEVICE_ID"]
    )
  end

  desc "Run banner integration tests"
  lane :banner_integration_test do
    clear_derived_data
    scan(
      scheme: "UnityAdsBannerIntegrationTests",
      code_coverage: true,
      project: "UnityAds.xcodeproj",
      reset_simulator: true
    )
  end

  desc "Run static analysis"
  lane :analyze do
    xcodebuild(
      project: "UnityAds.xcodeproj",
      scheme: "UnityAds",
      configuration: "Debug",
      clean: true,
      build: true,
      output: "/tmp/",
      xcargs: "analyze",
      output_directory: "./",
      destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\""
    )
  end
end
